version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/openssh-sftp-error"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/openssh-sftp-client-lowlevel"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/sftp-test-common"
    schedule:
      interval: "daily"
