[package]
name = "openssh-sftp-client"
version = "0.1.0"
edition = "2021"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Data format used to communicate with openssh mux server."
repository = "https://github.com/NobodyXu/openssh-sftp-client"

keywords = ["ssh", "multiplex", "async", "network", "sftp"]
categories = ["asynchronous", "network-programming", "api-bindings"]

[workspace]
members = [
    "child_io_to_pipe",
]

[dependencies]
thiserror = "1.0.29"
awaitable = "0.3.0"
concurrent_arena = "0.1.2"

derive_destructure2 = "0.0.1"

openssh-sftp-protocol = "0.16.0"

# Since concurrent_arena uses dependency parking_lot anyway,
# enabling feature parking_lot on tokio does not pull in any new dependency.
tokio = { version = "1.11.0", features = ["io-util", "parking_lot", "sync"] }

tokio-io-utility = "0.3.0"
tokio-pipe = "0.2.8"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros", "process"] }
once_cell = "1.8.0"
tempfile = "3.1.0"

# Since openssh-sftp-client forbids unsafe code, I have
# to put these code in another workspace.
child_io_to_pipe = { path = "child_io_to_pipe" }
