[package]
name = "openssh-sftp-client"
version = "0.1.0"
edition = "2021"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Data format used to communicate with openssh mux server."
repository = "https://github.com/NobodyXu/openssh-sftp-client"

keywords = ["ssh", "openssh", "multiplex", "async", "network", "sftp"]
categories = ["asynchronous", "network-programming", "api-bindings"]

[dependencies]
parking_lot = "0.11.2"
thunderdome = "0.5.0"

serde = { version = "1.0", features = ["derive"] }
ssh_format = "0.5.1"

bitflags = "1.3.2"
vec-strings = { version = "0.2.0", features = ["serde"] }

thiserror = "1.0.29"
pin-project = "1"

tokio = { version = "1.11.0", features = ["io-util", "rt", "sync", "parking_lot"] }
tokio-pipe = "0.2.5"
tokio-async-write-utility = "0.1"
