[package]
name = "openssh-sftp-client"
version = "0.1.0"
edition = "2021"

authors = ["Jiahao XU <Jiahao_XU@outlook.com>"]

license = "MIT"
description = "Data format used to communicate with openssh mux server."
repository = "https://github.com/NobodyXu/openssh-sftp-client"

keywords = ["ssh", "multiplex", "async", "network", "sftp"]
categories = ["asynchronous", "network-programming", "api-bindings"]

[dependencies]
thiserror = "1.0.29"
once_cell = "1.8.0"
generic-global-variables = "0.1.1"

parking_lot = "0.11.2"
thunderdome = "0.5.0"

openssh-sftp-protocol = "0.9.0"

tokio = { version = "1.11.0", features = ["io-util"] }
tokio-io-utility = "0.1.1"

[dev-dependencies]
tokio = { version = "1.11.0", features = ["rt", "macros", "process"] }
